# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s= "Hi there sam"
x= s.split()
print(x)

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
planet = "Earth"
diameter= 12742
print=("The diameter of {} is {} kilometers.".format(planet,diameter))

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d ={'k1' :[1,2,3,{'Tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
np.zeros(10)

array([0.,0.,0.,0.,0.,0.,0.,0.,0.,0.])

In [ ]:
import numpy as np
np.ones(10)*5

array([5.,5.,5.,5.,5.,5.,5.,5.,5.,5,])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arrange(20,36,2)
print("Arrange of all the even integers from 20 to 35")
print(array)

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a= np.array([1,2,3])
b= np.array([4,5,6])
arr=np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import pandas as pd
data=[[0,1],[2,3][4,5]]
df=pd.DataFrame(data)
print(df)

  0 1
0 0 1
1 2 3
2 4 5

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
per1=pd.date_range(start='1-01-2023', end='10-02-2023')
for val in per1:
  print(val)
  

2023-08-06 00:00:00
2023-08-07 00:00:00
2023-08-08 00:00:00
2023-08-09 00:00:00
2023-08-10 00:00:00
2023-08-11 00:00:00
2023-08-12 00:00:00
2023-08-13 00:00:00
2023-08-14 00:00:00
2023-08-15 00:00:00
2023-08-16 00:00:00
2023-08-17 00:00:00
2023-08-18 00:00:00
2023-08-19 00:00:00



## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists=[[1,'aaa',22][2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists)
print(df)

  0   1  2
0 1 aaa 22
1 2 bbb 25
2 3 ccc 24